### ISSUE TITLE
Test 4 OVAs and review documentation as an end user 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#107]
Follow the steps here: https://github.com/k8-proxy/GW-proxy

1.- Deploy the 4 OVAs
2.- Validate documentation
3.- Make sure everything is correctly documented
4.- Provide feedback on areas missed in the documentation
5.- Provide feedback on areas that can be improved: steps that can be automated to improve the process

**Comment by svf97** [comment]
- all OVAs were deployed and tested according to documentation
- **only change:** for [minio proxy OVA](https://github.com/k8-proxy/GW-proxy#minio-proxy-ova), in the directory `k8-reverse-proxy/stable-src`, the file `gwproxy.env` must have **ROOT_DOMAIN** set to `local.glasswall-icap.com` instead of `glasswall-icap.com` in order to access [proxied minio server](http://minio.server.local.glasswall-icap.com/)

**Comment by svf97** [comment]
**Update**:

previous comment on the issue was resolved in this [PR](https://github.com/k8-proxy/GW-proxy/pull/117)
