### ISSUE TITLE
Test OVAs in ESXi 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#116]
1.- Follow steps here: https://github.com/k8-proxy/GW-proxy to test the 4 OVAs
2.- Create an updated readm me with updated instructions to follow in ESXi

**Comment by nirvishek** [comment]
Deployed ICAP ova from controller console (kept getting cancelled while deploying directly from local due to network issues), got a number of issues regarding ovf upload, will update in readme. Testing icap and glasswall-engineering deployment now.

**Comment by dtollaku** [comment]
@nirvishek we will not need anymore glasswall-engineering deployment at this moment. We will let you know later.

**Comment by MaNe2020** [comment]
@GINAGC @dtollaku do we still need to deploy all of the OVAs. I created Minio Server one but experienced some issues during the really lengthy process. And it also seems there is no more avl IPs to created these. 
I can start deploying ICAP, Minio Server and Minio Proxy on the same VM, since they are closely connected but this will pick up a bit more resources.
