### ISSUE TITLE
Test ICAP server VM

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#150]
Test @azopat  provided instructions for the creation and deployment of the ICAP server OVA, the instructions are found here:
https://github.com/k8-proxy/GW-proxy/blob/icap-esxi/OVAs-creation/icap-server-ova.md

**Comment by svf97** [comment]
- creating a VM by cloning an existing VM:
   - cloning a VM isn't an option during this test
   - VM hardware requirements aren't mentioned to create a VM from scratch
- importing OVA on esxi02:
   - importing failed due to the following errors:
![Screenshot from 2020-12-02 14-55-49](https://user-images.githubusercontent.com/60857664/100875446-af018b80-34ae-11eb-9d97-77665c6ca148.png)
![Screenshot from 2020-12-02 14-56-11](https://user-images.githubusercontent.com/60857664/100875454-b163e580-34ae-11eb-8e8c-6089bfdb05b1.png)

**Comment by GINAGC** [comment]
@MaNe2020 please put on hold this, it is not working.

**Comment by mahnouman** [comment]
Hello @azopat I tried the OVA on my own and I got this error right away when uploading the OVA:

![image](https://user-images.githubusercontent.com/5932628/100878130-6cda4900-34b2-11eb-9aa7-321a93f9639d.png)

**Comment by azopat** [comment]
@mahnouman  it looks like @svf97  was able to start it now. So not sure why you are having that issue

**Comment by svf97** [comment]
> @mahnouman it looks like @svf97 was able to start it now. So not sure why you are having that issue

@azopat the VM will work, but the warning is still there

**Comment by MariuszFerdyn** [comment]
I think if you Ignore it the VM will be imported... I met it before and will investigate.

**Comment by svf97** [comment]
update on imported version of ICAP:
  - warning is expected to happen, but can be ignored for the time being
  - VM credentials were not in documentation
  - change VM's IP with `sudo vi /etc/netplan/01-netcfg.yaml` in only the first IP address
  - step#5  yielded the following error:
![image](https://user-images.githubusercontent.com/60857664/100903906-1a5b5580-34cf-11eb-9b5d-abc90ce056e2.png) so it was replaced with the following command `kubectl -n icap-adaptation edit svc/icap-svc-host`, where we edit external IP as per VM IP
  - verifying services are up and running:
    - `kubectl -n icap-adaptation get pods` to make sure pods are running
    - `telnet VM_IP 1344` to make sure ICAP is running
    - you can also test with a PDF `c-icap-client -f ./FILE_NAME.pdf -i VM_IP -p 1344 -s gw_rebuild -o ./REBUILD_NAME.pdf -v`

**Comment by GINAGC** [comment]
@svf97 send a PR with the documentation updates. @MaNe2020 please test this one too.
