### ISSUE TITLE
Test Support OVA

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#185]
Documentation: https://github.com/k8-proxy/GW-proxy/blob/master/OVAs-creation/SupportServer.md

OVA link to be added soon: https://github.com/k8-proxy/GW-proxy/tree/master/OVAs-creation

**Comment by svf97** [comment]
- Install the Operating System in VM:
  - step 3:
    - first 2: we can't do ssh and apt-get update without configuring IP 
    - last step: minimum packages are not clarified
  - steps 4 and 5 were repeated
- Deploy Solution and export OVA:
  - when running `sudo systemctl enable bind9` I got the following error: 
>     Failed to enable unit: Refusing to operate on alias name or linked unit file: bind9.service
   but starting and restarting the service, work
  - when modifying bind files please use `sudo` when using `vi /etc/..`
  - remove 'cat' from `vi cat /etc/bind/rndc.key`
  - please use `sudo` with `rm /etc/resolv.conf`
  - after following steps for "reconfigure resolver", I wasn't able to install webmin, or do `sudo apt update` due to `Temporary failure resolving` or `Temporary failure in name resolution` this was shared with @MariuszFerdyn and waiting for respond

**Comment by svf97** [comment]
- temporary failure issue is temporarily fixed by changing nameserver to 8.8.8.8 in `/etc/resolv.conf` but @MariuszFerdyn said he will be investigating 
- no webmin credentials provided in doc for the step "Add PKI to Webmin"
- when running `make-cadir easyrsa`

> easyrsa exists. Aborting.
> Usage: /usr/bin/make-cadir DIRECTORY
> Creates a *new* directory and prepares it to be used as a (CA) key management directory (to create and store keys and certificates).

- based on the previous comment, also running `./easyrsa init-pki` results in:

> -bash: ./easyrsa: No such file or directory

**Comment by svf97** [comment]
- Add PKI to Webmin:
  - username and password are the same as the VM's
  - when navigating to `https://IP_ADDRESS:10000/webmin/edit_mods.cgi?xnavigation=1` > Webmin Modules > From HTTP or FTP URL > add `http://www.webmin.com/download/modules/certmgr.wbm.gz` and leave everything else at default > Install Module
- Install Easy-RSA:
  - the command `mkdir /opt/easyrsa` should not be there
- Configure Guacamole:
  - for the command `echo -n yourpassword | openssl md5', copy the md5 of the password used as it will be added in the file `etc/guacamole/user-mapping.xml` in `password` 
- when navigating to `https://VM_IP:10000/certmgr/gencsr.cgi?xnavigation=1`, pick `Generate Key and Certificate Signing Request (CSR)`
- it isn't clear what the steps are for DNS

**Comment by svf97** [comment]
final comments for testing support OVA:
- when configuring file `/etc/guacamole/user-mapping.xml`:
  - after adding the generated password from previous step, change hostname to VM's IP address so the file should look like this:( **note**: please only modify the IP (hostname for one connection) and username ( as per VM's username) so the indentation isn't modified. the file below is just an example), this will allow you to ssh into the VM from a browser without step 7 (guacamole)

> <user-mapping>
>     <authorize
>             username="admin"
>             password="49aa66843380c377e93b198b966eb699"
>             encoding="md5">
> 
>         <connection name="Ubuntu20.04-Server">
>             <protocol>ssh</protocol>
>             <param name="hostname">91.109.25.81</param>
>             <param name="port">22</param>
>             <param name="username">glasswall</param>
>         </connection>
>     </authorize>
> </user-mapping>    

- when doing the step for `Generate Key and Certificate Signing Request (CSR)` as per earlier comment, this is how the configuration file should look like:
![image](https://user-images.githubusercontent.com/60857664/101491360-52014c00-396c-11eb-9528-8b97730bef00.png)

- steps for DNS:  
  - navigate to `https://IP_ADDRESS:10000/bind8/?xnavigation=1` > Under Existing DNS Zones > glasstest.com. You should get this screen, after clicking on glasstest.com
![image](https://user-images.githubusercontent.com/60857664/101494034-80ccf180-396f-11eb-9ece-bcb8f4e0b56c.png)
  - Click on addresses. You will see this:
![image](https://user-images.githubusercontent.com/60857664/101494107-97734880-396f-11eb-8806-e3973cc02830.png)
  - For testing: **name**: third , **address**: 8.8.8.8 > create
  - in the VM, run `sudo systemctl restart bind9.service`
  - In the VM, run `nslookup` > `server 127.0.0.1` > third.glasstest.com (or the name created in previous test). You should get a result that looks like this: 

> Server:		127.0.0.1
> Address:	127.0.0.1#53
> 
> Name:	third.glasstest.com
> Address: 8.8.8.8
