### ISSUE TITLE
Test traffic generator OVA and doc

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#192]
Please test OVA for Traffic gen: https://github.com/k8-proxy/GW-proxy/tree/master/OVAs-creation and the documentation:

https://github.com/k8-proxy/aws-jmeter-test-engine/blob/master/jmeter-icap/instructions/How-to-Deploy-OVA.md

https://github.com/k8-proxy/aws-jmeter-test-engine/blob/master/jmeter-icap/instructions/How-to-Generate-Load-with-OVA.md

**Comment by svf97** [comment]
- step 11: `cd /opt/git/script` , this directory is actually, `/opt/script`
- ICAP Endpoint URL entered as presented in the image, and since there was no result in doc for comparison, this was the results (25 users, all other values were left as default)
![Screenshot from 2020-12-06 21-43-21](https://user-images.githubusercontent.com/60857664/101290629-32531200-380c-11eb-8a07-9f31986f8146.png)
