### ISSUE TITLE
Kubernetes setup assessment 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#222]
Please investigate the possible causes and fixes for the issues below:

- Health check command to see Icap/kubernetes pods is up
- Include octant in kubernetes image
- Figure out why server take so long to start
- Check why pod janitor is not running
- Investigate why memory is limited to 6G

Please check if those issues are applicable to both ICAP and Proxy clusters or either of them.

**Comment by mahnouman** [comment]
Hi @azopat please check the information provided in #237 & #239 ,, thanks

**Comment by mahnouman** [comment]
@pranaysahith please work with @azopat on this, thank you

**Comment by azopat** [comment]
@mahnouman 
Check why pod janitor is not running :
- PR created to fix the issue, please merge - https://github.com/filetrust/icap-infrastructure/pull/337

Investigate why memory is limited to 6G
As we know, it's because of the rebuild pod requesting much ressources. It can be tweaked here : 
https://github.com/filetrust/icap-adaptation-service/blob/develop/pkg/pod.go#L156
