### ISSUE TITLE
Release process for OVAs

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#289]
Think about the release process that we need and what information we need to include in the release. think of:
Semantic Versioning

For example yaml file with information about the OVA. So, typically the VM would include the VM type (For example: Proxy), release date, version number, Usage (For example: gov.uk ,,,,, so it means this is a proxy for gov.uk).

So please create a template YAML file and think of a release process that should be followed.

**Comment by svf97** [comment]
@MaNe2020 and I will have a meeting regarding finalizing this, but as a draft: 

since we have [14](https://github.com/k8-proxy/GW-proxy/blob/master/OVAs-creation/readme.md) OVAs, we can divide them into 3 main ova types [server, client, and website]

### OVA Types
**server**: HAProxy-ICAP, ICAP-Server, Shared Storage, Traffic Gen, support, proxy, and monitoring
**client**: ICAP-Client, Linux-Desktop
**website**: minio-server, wordpress, file-drop, gov.uk, HAProxy-web

### Version Number
- version release x.y.z, where x defines a major change, y defines a minor change, and z defines a patch 
  - initial development release 0.1.0 (increment from here)
  - pre-release [1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0] 
  - initial production release 1.0.0 (increment from here)

### YAML file example for a server

> ova-name: icap-server
> ova-type: server
> ova-size: 4.6 GB
> release-date: 11-12-2020
> version-number: v1.0.0
> description: Kubernetes based ICAP server/CDR engine
> usage: serve as file rebuilder

### YAML file example for a website

> ova-name: minio-server
> ova-type: website
> ova-size: 1.9 GB
> release-date: 11-12-2020
> version-number: v1.0.0
> description: minio server VM
> usage: access minio.server from VM's IP

### YAML file example for a client

> ova-name: icap-client
> ova-type: client
> ova-size: 1.6 GB
> release-date: 11-12-2020
> version-number: v1.0.0
> description: docker-based ICAP client
> usage: rebuild clean files using docker ICAP client and ICAP server

**Comment by MaNe2020** [comment]
@svf97 I really like what example.
Here is more or less the same just added: fixes, new_features and dependencies.
@GINAGC we will come with some final version tomorrow.


### YAML file template

> <OVA_NAME>: 
  > virtual_machine_type:
    > server:
          - HAProxy-ICAP
          - ICAP-Server
          - Shared Strage
          - Traffic Generator
          - Support
          - Proxy
          - Monitoring
    > client:
          - ICAP-Client
          - Linux-Desktop
    > website:
          - Minio-server
          - Wordpress
          - File-Drop
          - gov.uk
          - HAProxy-web
  > usage: 
  > description: 
  > release_date: mm/dd/yyyy
  > version_number: 1.0.0 
  > dependences:
  > fixes:
  > new_features: 


### YAML file example

> SOW_REST_OVA: 
  > virtual_machine_type:
    - website
  > usage: Proxied file-drop.com website
  > description: Deploys file-drop.com on isolated VM.
  > release_date: 12/15/2020
  > version_number: 1.0.0 
  > dependences: none
  > fixes: stronger password
  > new_features: automatic network change



I checked this nice explanation about semantic versioning: https://medium.com/the-non-traditional-developer/semantic-versioning-for-dummies-45c7fe04a1f8
We should probably add few details about this in release guide.

**Comment by MaNe2020** [comment]
@GINAGC here is how I see our release process. But will think a bit more about this. Just a first draft.

![ReleaseProcess](https://user-images.githubusercontent.com/70108899/102262962-00306700-3f14-11eb-9ac7-308cd4bdbcce.png)

**Comment by GINAGC** [comment]
Hi @MaNe2020 yes, Doviana and I have talked about it and starting in January we want to use Friday for planning instead of Monday. So in the release plan, we should release new OVAs on Wednesday and test on Thursday.

**Comment by MaNe2020** [comment]
@GINAGC take a look: https://github.com/k8-proxy/GW-proxy/blob/master/Release/release_process.md
@svf97 merged all of the above and some other thoughts we had into README file.
Let us know if you have any feedback.

**Comment by GINAGC** [comment]
@MaNe2020 this looks great!

@mahnouman take a look to the yaml file, let us know if anything else should be added or if we can start to implement it.
