### ISSUE TITLE
Check SOW version updates

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#297]
Please check if the parent SoW version is still using Azure or switched to something else,, this is for the Mgmt and events:
https://github.com/filetrust/icap-infrastructure

**Comment by mahnouman** [comment]
Hi @samarthdd please assist @azopat in this, thanks

**Comment by azopat** [comment]
hi @mahnouman 
As discussed on slack, we couldn't have the feature out of the box from the existing services because the event submission service still leverage azure file to send the event data.
The SOW team changed the transaction api service to use local file (PVC) but haven't yet updated the event processing.
So i am working on updating the event processing code in order to support it. The code is hosted here : https://github.com/filetrust/event-submission-service
Let me know if you need more clarifications

**Comment by GINAGC** [comment]
This is done
