### ISSUE TITLE
Add support for sending logs and stats to our monitoring servers 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#331]
Add support for sending logs and stats to our monitoring servers (Elastic Search and Grafana). As minimum, it should include:

1.- Data from health checks and configuration
2.- Data from deployment / VM destruction

**Comment by mahnouman** [comment]
@faisaladnanpeltops please highlight how the running scripts would send alerts, is it syslog? or something else, thanks

**Comment by faisaladnanpeltops** [comment]
@mahnouman , it's a typical log aggregation method. See the processing flow below:

1. The application (nginx, reverse-proxy, sow, etc) create log files under log directories (e.g. /var/log)
2. Fluentd scan the log directories, and send each line as json record to an elasticsearch index
3. Kibana read the index and visualise it.

Fluentd can also support syslogd. The flow is:
1. The application send its log to Fluentd that acts as syslogd.
2. Fluentd sends each line as json record to an elasticsearch index
3. Kibana read the index and visualise it.

Fluentd support syslogd tcp or udp. It also support log format rfc3164 or rfc5424.

Using log files is preferable because:
1. No changes in the application is required. 
2. The fluentd configuration is simple.

**Comment by GINAGC** [comment]
Moving to the next release to continue the work, will add Dinis feedback later today.
