### ISSUE TITLE
Create FAQ for Program ICAP 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#364]
1.- Go to the next board: https://github.com/filetrust/program-icap/wiki/Use-of-Zenhub-Epics-in-the-Planning-and-Development-Process#workspaces/icap-program-5f3123b690ea7c0015de3bff/board?filterLogic=any&repos=285523569,285650475,302658624,302602061,303953050,303653424,302657061,304604761,306312421,306375287

2.- Filter by Label "FAQ"

3.- Create an MD page FAQ page with the information from all the issues filtered in the previous step.

**Comment by kerempg** [comment]
1) The FAQ.md page is created & pull requested:
https://github.com/kerempg/program-icap/blob/patch-1/FAQ.md

2)  Screenshots will be pushed under:
program-icap/doc/
so that the screenshots will be visible in FAQ.md.

**Comment by kerempg** [comment]
1- filetrust/program-icap#288
pull request has been created for FAQ.md

2- for https://github.com/filetrust/program-icap which I'm given access, I can not push screenshots via VSCode, it gives the attached error:
![neden (2)](https://user-images.githubusercontent.com/2248132/108160122-85452180-70f9-11eb-8ba9-08ad975cb527.png)


is there any way around to overcome the problem of not being able to push https://github.com/filetrust/program-icap via VSCode?
or
or any other person, who has write access, can insert the screenshots into the repository so that screenshots can be used in FAQ.md
https://drive.google.com/drive/folders/1BnoEzhLuk0jWZ-sUPuiYaQWz5HfQAsUF?usp=sharing
