### ISSUE TITLE
Document how to test offline on ESXi and AWS (file drop and ICAP server)

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#382]

**Comment by naderaly** [comment]
# Test offline ICAP-server on ESXi

* Open **Controller**'s machine **Console** and login to [esxi01.glasswall-icap.com](esxi01.glasswall-icap.com) from firefox.
* From **Virtual Machines** Select **Create / Register VM**

![image](https://user-images.githubusercontent.com/58347752/110112081-ec312e80-7db9-11eb-905b-96f41befe786.png) 

* Select **Deploy a virtual machine from an OVF or OVA file** & Enter a virtual machine name then select the latest **ICAP OVA**
* Press Next till **Deployment options** page & make sure that **VM Network** is **VMs** & Disable the power on automatically option.

![image](https://user-images.githubusercontent.com/58347752/110120737-1ee12400-7dc6-11eb-81aa-4a7e9e963743.png)

* Press Next and Finish VM registration.
* Close Controller VM console and wait till the OVA upload is done.
* Find your Imported VM and press on Edit, Then modify the CPU to be 4 and Memory to be 8 GB

![image](https://user-images.githubusercontent.com/58347752/110121183-c199a280-7dc6-11eb-983d-dffc1bf59bc3.png)

* Power on the VM, open console and wait till the login prompt (You may need to press Enter)
* login with the provided credentials and wait 5 mins.
* Now since the VM is connected to VMs network adapter it will be auto assigned with IP address, enter the following command to find it

```bash
ip -4 a
```

![image](https://user-images.githubusercontent.com/58347752/110122388-3b7e5b80-7dc8-11eb-9c27-04b51dd6e4c9.png)

* Find **eth0** & the IP will be the one after **inet** , 192.168.30.22 in the screenshot above
* Make sure the all pods are running by running 

```bash
kubectl get pod -A
```

![image](https://user-images.githubusercontent.com/58347752/110122541-6ec0ea80-7dc8-11eb-975c-05279156335f.png)

* Now, open **Offline-Controller** VM (which is an ubuntu VM with graphical user interface not connected to the internet) console.
* Login and open hosts file 

```bash
sudo nano /etc/hosts
```

* Add the following line (or edit if exists)

```bash
192.168.30.22 management-ui.glasswall-icap.com
```

 ![image](https://user-images.githubusercontent.com/58347752/110123302-6a490180-7dc9-11eb-8bc3-9211ae4a0588.png)

* Open firefox and open the following url https://management-ui.glasswall-icap.com/

![image](https://user-images.githubusercontent.com/58347752/110123871-1d195f80-7dca-11eb-9621-7121aa9547f2.png)



# Test offline FileDrop on ESXi

* Open **Controller**'s machine **Console** and login to [esxi01.glasswall-icap.com](esxi01.glasswall-icap.com) from firefox.
* From **Virtual Machines** Select **Create / Register VM**

![image](https://user-images.githubusercontent.com/58347752/110112081-ec312e80-7db9-11eb-905b-96f41befe786.png) 

* Select **Deploy a virtual machine from an OVF or OVA file** & Enter a virtual machine name then select the latest **FileDrop OVA**
* Press Next till **Deployment options** page & make sure that **VM Network** is **VMs** 

![image](https://user-images.githubusercontent.com/58347752/110113275-9067a500-7dbb-11eb-9417-6e0714b246c6.png)

* Press Next and Finish VM registration.
* Close Controller VM console and wait till the OVA upload is done.
* Find your Imported VM and Open console and wait till the login prompt (You may need to press Enter)
* login with the provided credentials and wait 5 mins (till some logs are printed on screen).
* Run the following command .

```bash
./flush_iptables.sh
```

* Now since the VM is connected to VMs network adapter it will be auto assigned with IP address, enter the following command to find it

```bash
ip -4 a
```

![image](https://user-images.githubusercontent.com/58347752/110115872-5e584200-7dbf-11eb-9cc3-6f6583bf6e1d.png)

* Find **eth0** & the IP will be the one after **inet** , 192.168.30.19 in the screenshot above
* Make sure the all pods are running by running 

```bash
kubectl get pod -A
```

![image](https://user-images.githubusercontent.com/58347752/110119443-7d0d0780-7dc4-11eb-84d9-1ef3e112f3cb.png)

* Now, open **Offline-Controller** VM (which is an ubuntu VM with graphical user interface not connected to the internet) console, open firefox & enter the filedrop vm IP in the URL 

![image](https://user-images.githubusercontent.com/58347752/110119854-00c6f400-7dc5-11eb-94fd-daa3759df6cf.png)

**Comment by dtollaku** [comment]
@naderaly can you add these on a readme file please

**Comment by naderaly** [comment]
hello @dtollaku , readme file was created and sent to @svf97 as she will update the wiki

**Comment by svf97** [comment]
@dtollaku please approve this PR https://github.com/k8-proxy/glasswall-servers-eval/pull/3/

**Comment by MaNe2020** [comment]
@naderaly @GINAGC @svf97 
I am still getting issue with ICAP Offline.
After starting VM, connected to "New port Group" with 4CPU, 8GB RAM and after login getting this
![image](https://user-images.githubusercontent.com/70108899/110767723-d8247b80-8256-11eb-95b5-6cf870f2b358.png)

tried flushing ip tables and restarting k3 but getting this
![image](https://user-images.githubusercontent.com/70108899/110768090-305b7d80-8257-11eb-932d-43f6b2b83fcb.png)

Can someone checkout this? On ESXi is the machine is named ICAPOffMarija.

**Comment by naderaly** [comment]
Hello @MaNe2020 , we are not connection to "New port Group" anymore 
![image](https://user-images.githubusercontent.com/58347752/110796703-eb4c4100-8280-11eb-9f19-dce83b38caf8.png)

**Comment by GINAGC** [comment]
Documentation is in https://github.com/k8-proxy/glasswall-servers-eval/blob/main/test_offline_FD.md
